# Site settings
title: Malawi Measles RCM 2017
safe: false
source: app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

baseurl: "/measles"

permalink: pretty
